### ISSUE TITLE
Detection of paid articles

### ISSUE THREAD

**Issue by wi18b088** [wi18b088/HEFscraper#1]
Sometimes, the PDF Scraper cannot find a PDF Download button either way. These events are logged. 
The reason is, that those articles are paid articles. There is only the abstract available. The Text Scraper pulls the abstract in this case.
Unfortunately, I found no way to filter out paid articles in the Springer Link search, so they will inevitably end up in the results CSV.
We need a detection method for paid articles and exclude them.

**Comment by Sjoerd266** [comment]
http://link.springer.com/article/10.1007/s13272-015-0176-x example link. 

![image](https://user-images.githubusercontent.com/35135243/97991674-09d99180-1de2-11eb-9f72-dd2632bb2a4a.png)
If statement to work around this?

**Comment by Sjoerd266** [comment]
Left on hold for now due to redundancy. It's added to the script, but seems to be skipped anyway.
